include:
  - project: 'dti/agd/templates/ci-templates-javascript'
    ref: master
    file: 'nest.yml'

variables:
  AUTOMATIC_DEPLOYMENT_ON_QA: "true"
  NODE_VERSION: "20"
  K8S_APP_PORT: "3001"

deploy:qa:
  environment: qas

deploy:prd:
  environment: prd
