apiVersion: v1
kind: ConfigMap
metadata:
  name: ${K8S_CONFIG_MAP_NAME}
  namespace: ${K8S_NAMESPACE}
data:
  SWAGGER_SERVERS_LIST: ${SWAGGER_SERVERS_LIST}
  POSTGRESQL_HOST: ${POSTGRES_HOST}
  POSTGRESQL_PORT: "${POSTGRES_PORT}"
  POSTGRESQL_USERNAME: ${POSTGRES_USERNAME}
  POSTGRESQL_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRESQL_NAME: ${POSTGRES_DATABASE}
  