apiVersion: v1
kind: ConfigMap
metadata:
  name: ${K8S_CONFIG_MAP_NAME}
  namespace: ${K8S_NAMESPACE}
data:
  SWAGGER_SERVERS_LIST: ${SWAGGER_SERVERS_LIST}
  POSTGRES_HOST: ${POSTGRES_HOST}
  POSTGRES_PORT: "${POSTGRES_PORT}"
  POSTGRES_USERNAME: ${POSTGRES_USERNAME}
  POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
  POSTGRES_DATABASE: ${POSTGRES_DATABASE}
  MAIL_HOST: ${MAIL_HOST}
  MAIL_PORT: "${MAIL_PORT}"
  MAIL_USERNAME: ${MAIL_USERNAME}
  MAIL_PASSWORD: ${MAIL_PASSWORD}
  MAIL_AUTH: ${MAIL_AUTH}
  MAIL_FROM: ${MAIL_FROM}
