enum ENV_VARIABLE_NAMES {
    SWAGGER_SERVERS_LIST = "SWAGGER_SERVERS_LIST",
    OPENID_WELL_KNOWN_URL = "OPENID_WELL_KNOWN_URL",
    ISSUER = "AUTH_SERVER_ISSUER",
    AUDIENCE = "AUDIENCE",
    SERVICE_REGISTRY_ENVIRONMENT = "SERVICE_REGISTRY_ENVIRONMENT",
    SERVICE_REGISTRY_URL = "SERVICE_REGISTRY_URL",
    SERVICE_REGISTRY_DISCOVERY_SYSTEM_NAME = "SERVICE_REGISTRY_DISCOVERY_SYSTEM_NAME",
    POSTGRES_HOST = "POSTGRES_HOST",
    POSTGRES_PORT = "POSTGRES_PORT",
    POSTGRES_USERNAME = "POSTGRES_USERNAME",
    POSTGRES_PASSWORD = "POSTGRES_PASSWORD",
    POSTGRES_DATABASE = "POSTGRES_DATABASE",
    MONGODB_USERNAME = "MONGODB_USERNAME",
    MONGODB_PASSWORD = "MONGODB_PASSWORD",
    MONGODB_DATABASE = "MONGODB_DATABASE",
    MONGODB_HOST = "MONGODB_HOST",
    VALKEY_HOST = "VALKEY_HOST",
    VALKEY_PORT = "VALKEY_PORT",
    VALKEY_PASSWORD = "VALKEY_PASSWORD"
}

export default ENV_VARIABLE_NAMES;
