import { NestFactory } from "@nestjs/core";
import { AppModule } from "./app.module";
import { DocumentBuilder, SwaggerModule } from "@nestjs/swagger";
import { version } from "../package.json";
import ItemEntity from "./modules/items/entities/item.entity";
import ENV_VARIABLE_NAMES from "./utils/env_variable_names";
import { ConfigService } from "@nestjs/config";

async function bootstrap() {
    const app = await NestFactory.create(AppModule);

    app.enableCors();

    const configService = app.get<ConfigService>(ConfigService);

    const swaggerConfig = new DocumentBuilder()
        .setTitle("solarwebappback")
        .setDescription(
            "Items API generated by Developers Suite Code Generator.",
        )
        .setVersion(version)
        .setExternalDoc("JSON", "/api/json");

    const swaggerServersList: string = configService.get(
        ENV_VARIABLE_NAMES.SWAGGER_SERVERS_LIST,
    );

    if (swaggerServersList) {
        swaggerServersList
            .split(",")
            .forEach((server) => swaggerConfig.addServer(server));
    }

    // Register a simple GET handler for /api to return a basic message.
    // This is placed before Swagger is mounted so a plain "Hello World!" is
    // returned when the browser visits /api.
    const server = app.getHttpAdapter().getInstance() as any;
    server.get("/api", (_req: any, res: any) => {
        res.send("Hello World!");
    });

    const document = SwaggerModule.createDocument(app, swaggerConfig.build(), {
        extraModels: [ItemEntity],
    });

    SwaggerModule.setup("api", app, document, {
        customSiteTitle: "solarwebappback",
        jsonDocumentUrl: "/api/json",
    });

    await app.listen(3000);
}
bootstrap();